version: "3"
services:
  vue-app:
    image: brandtrobert/releaseboardapp:vue-app
    ports:
      - 80:80
    links:
      - api
  api:
    image: brandtrobert/releaseboard:api
    links:
      - mongo
    expose:
      - 3000
  mongo:
    image: mongo:latest
    volumes:
      - /var/lib/mongo
    expose:
      - 27017
